
default_platform(:android)

platform :android do
  desc "Lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor dev --target=lib/main_dev.dart"
    firebase_app_distribution(
      app: "1:788195993317:android:170a8b7dd0737b25e5960c",
      firebase_cli_token: "1//03DgHGo3cm-SECgYIARAAGAMSNwF-L9IrAaYqOYSY4rNpftNYjEDhD2odJaKcGYAhE1Ci9umTSuIj09v_yNGCwuBzB76iwU5V7ds",
      testers: "mohammedmokhtar932@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
      release_notes: "Lots of amazing new features to test out!"
    )
  end
end
